from django.conf.urls import patterns, include, url

urlpatterns = patterns('account.views',
    url(r'^register/$','register_user'),
    url(r'^login/$','login'),
    url(r'^logout/$','logout'),
    url(r'^welcome_user/$', 'welcome_user'),
    url(r'^invalid_login/$', 'invalid_login'),
    url(r'^change_profile/$', 'change_profile'),
    url(r'^view_profile/(?P<user_id>\d+)/$','view_profile'),
    url(r'^change_password/$', 'change_password'),
    url(r'^confirm/(?P<activation_key>\w+)/$', 'confirm'),
    url(r'^confirmation_resend/$', 'confirmation_resend'),
    url(r'^forget_password/$', 'forget_password'),
    url(r'^first_login/$', 'first_login'),
    url(r'^add_follower/(?P<user_id>\d+)/$', 'add_follower'),
    url(r'^remove_follower/(?P<user_id>\d+)/$', 'remove_follower'),
    url(r'^get_followers/(?P<user_id>\d+)/$', 'get_followers'),
    url(r'^get_following/(?P<user_id>\d+)/$', 'get_following'),
	url(r'^search/$', 'search'),
	url(r'^display_all_users/$', 'display_all_users'),
)
